# Generated by Django 3.2.15 on 2023-09-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='location',
            new_name='coordinates',
        ),
    ]
