# Generated by Django 3.2.15 on 2023-09-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_fields_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='input_data',
            field=models.CharField(default=[], max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fields',
            name='coordinates',
            field=models.CharField(max_length=2000),
        ),
    ]
