# Generated by Django 3.2.15 on 2023-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230930_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
