# Generated by Django 3.2.15 on 2023-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_jobs_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='area',
            field=models.CharField(default='0.25', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fields',
            name='description',
            field=models.CharField(default='default', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fields',
            name='field_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
