# Generated by Django 3.2.15 on 2023-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20231001_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldjobrecords',
            name='complete_date',
            field=models.DateField(default='2023-10-02'),
            preserve_default=False,
        ),
    ]
