# Generated by Django 3.2.15 on 2023-10-03 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fieldjobrecords_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdatarotation',
            name='farm_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='users.farms'),
            preserve_default=False,
        ),
    ]
