# Generated by Django 3.2.15 on 2023-10-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cropdatarotation_farm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdatarotation',
            name='farm_id',
        ),
    ]
