"""
Django settings for djangofyp project.

Generated by 'django-admin startproject' using Django 4.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import ee
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-21vpopz41w0j$wiya*sv6)m39(7ai_nmo=b4q-%&4)3uow(mao'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_nextjs',
    'corsheaders',
    'rest_framework',
    'users',
    'backendapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'djangofyp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangofyp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'fyp2',
        'CLIENT': {
            'host': 'mongodb+srv://moeiz_1602:moeizjunaiddilawar@fyp.tnncwly.mongodb.net/',
            'username': 'moeiz_1602',
            'password': 'moeizjunaiddilawar'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')


# Also Make aure To set allowed_hosts to '*'

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

GEE_JSON_KEY_FILE = os.path.join(
    BASE_DIR, 'djangofyp\\first-parser-394719-161b1e1e6ec6.json')

# The service account email associated with the key
GEE_ACCOUNT = 'moeiz-shahzad@first-parser-394719.iam.gserviceaccount.com'

# The private key data from your JSON key file
GEE_PRIVATE_KEY = '''
-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCkhT9MNW806hoP\nv4BcFHaWi5qJ3HC6kMuBDfKLCcUtrxD0Ni3DxWCzGpXYvBsaU4Q706l6k3kzl5N+\nzdVp/7Wsl0ThnhX/WoYKuObO8Z5FOu2pqNCJdAQ/CIHy+6FoGYMpGrmoNW1dr8aK\nKv0rOy/gt9AuDdsu+jMIeO+O2oetfxNkCasiIc8yLcSynwkFjEkqGOECkRwyDhhr\npm4IZfrWOYdQWqI6932mZ69Sq7oaRklqfNUVJcv1XYBVfM/49Q1nQalNH/ys0CZb\nyY4eNZPb4xg7GX64xVQIOAEUPoCSfm74/K0hdb9EAbv6dfXYDGYQns1EyQThCJQV\n4OtRNBG/AgMBAAECggEADxk1bmqG+q2zV5elEY5FNdq5A4bqB40rR/w+Mplicadb\n4HWqbImMLtO1Rc85k4hvncf2iUvIdz4laKE+QTyY8S5uwV/vN+CYZZqDgCF3e3YF\ngqj9/mdZzmka9/A052dT/K05taC1mT/88ggw9Ms5QR/NaLSX1W9byJ7EqXEPu5HE\nmqrh4BHoG6IIo6KwbStdy7QfdDzqTRG2Y9dyubo/DhjR/0zKUyO3P3CGxbDFh9Jo\nXgKOmSM25gHgE7Kak4HPkiocUxonxvUA3dd9BJ/gjfgDEIaU2tcp50ZCsULN1+Xf\nHBcRGyHFFtQCb7lVCiMNH2uFcnopmFcbByZHe20UOQKBgQDjF5BhvCD/OVxRNiZP\nI/iU2EUk0QfgTrMl/rlwIEdws1Oy+rzAE7GubTC+UxJeRUCudVeHDkouzwO+XhjE\nrOZBp9ngZLXWlmJvV4yfz9FI2WF8ulpXsFbhplW0jBjyFiL+EPWMJdQdj0fW/Wkk\nducvuUvUdUa2BSoEMfYmL7iLiQKBgQC5dpzN7EI5suE7D4luBGcpr7R8kQiVS0Yy\n6EhUtUctDlLPXuImg4yegKrlwJpOlz4/6sjfdYKs3iEk7JJn3mAssBMgN+y36Asa\nIgnyBpdRw0DuKQQ3otok5chAVhz0Si/FLy/gFgFDW+8RExuj4U0VYG032P7+4aDU\nMcDRW/D5BwKBgQCr3mmnjnpqrz7vN8xGmTLJc+TguFL9sJJlbyNpeQSYhyARlTLF\nLCKNoJYDdVuxfTg20RgtXuNGCecLbKvSLgkWJ7L94Tq97ZMSMXB8gwwh1mOxwlgd\nhZg7r2et/Vnj3l0dbDhqmTawKIB2ddPdhR/zPonlgdzCZaYnBqkEvZkuAQKBgGlK\nE188n6ROD1wOSAEzcrXR0G9fjzXilCnWgSnF+HB1z0F3JoCi8jQR6/OfUnsHlgmH\nax6hgdxOBxcFT2C0eHkmRNVnqnYFwDfH10mVwFZkuPn8Qy6qv5lu8i7ENI/jhhc1\n4MIg+/qXuLNC29A/2hkmsxqfkLR2t22ACW1R+w4FAn9Z5YU9tbmxYFtwaHMYpSHM\n64Csx5FzyvEvr2MlNO8jyfnnmQ8pFV0Nk4Lyn2qg8RM4DljMbG7shHXErcpbLn0p\nL+6J9xdFdXkbWecr5pe45eggb7ETlKb04g7i+9RWjBDBQir02O/Fe9OzcvIJZ8P9\nGH3hiwIBk9Q4dkkBYA0z\n-----END PRIVATE KEY-----\n
'''


def initialize_gee():
    credentials = ee.ServiceAccountCredentials(
        email=GEE_ACCOUNT,
        key_file=GEE_JSON_KEY_FILE,
    )

    ee.Initialize(credentials)
    print(credentials)


initialize_gee()
